### ISSUE TITLE
t/01_date.t works only on 2014-12-29

### ISSUE THREAD

**Issue by eserte** [reneeb/Mojolicious-Plugin-FormFieldsFromJSON-Date#1]
See http://matrix.cpantesters.org/?dist=Mojolicious-Plugin-FormFieldsFromJSON-Date;reports=1#sl=7,1 for a time-sorted pass/fail overview.

**Comment by reneeb** [comment]
Uups, thanks for the bugreport. it is fixed with 300cfa3
