### ISSUE TITLE
Tests fail since 2015-01-01 (version 0.02)

### ISSUE THREAD

**Issue by eserte** [reneeb/Mojolicious-Plugin-FormFieldsFromJSON-Date#2]
Again there seems to be a date-related failure pattern. See http://matrix.cpantesters.org/?dist=Mojolicious-Plugin-FormFieldsFromJSON-Date%200.02;reports=1#sl=7,1

**Comment by reneeb** [comment]
Thanks for this report. But these are different issues ... I'll fix it...

**Comment by reneeb** [comment]
Fixed with 409a5e4 and 9e72036
